lang:
   cyrillic decoding: true
   commands:
      no access: "You don't have permission to use this command!"
      usage: "Usage: "
      fatal error: "Error occured executing command!"
      no station: "There is no such station or command."
      sit: "Sit in a cart on a station block, please."
      canceled: "Canceled!"
      destination: "Current destination: "
      invalid direction: "Invalid direction: "
      place block: "Place a node-block and a rail first!"
      place station: "Place a station-block and a rail first!"
      adding node: "Adding a new node..."
      adding station: "Adding a new station..."
      fail reason: "Fail! Reason: "
      adding success: "Successfully added!"
      removing: "Removing..."
      removing success: "Successfully removed!"
      stand over: "You must stand over a registered node!"
      no such node: "There are no nodes/stations at specified coordinates!"
      linking: "Linking..."
      linking success: "Successfully linked!"
      or: "or"
      and: "and"
      enter add node: "Enter this to add the node to the map: "
      enter add station: "Enter this to add the station to the map: "
      cannot break: "You cannot break a block registered as a node!"
      searching path: "Searching shortest path..."
      path not found: "Either you are at the destination station or path not found!"
      path found: "Path is found. Starting movement..."
      no destination: "Destination is not specified!"
      station: "Station"
      node: "Node"
      id: "Id"
      location: "Location:"
      x: "X"
      y: "Y"
      z: "Z"
      connection: "Connection:"
      north: "North"
      east: "East"
      south: "South"
      west: "West"
      name: "Name"
      no such command: "There is no such command for: "
      name reserved: "You cannot use this name!"
      arrived: "You arrived!"
      already location: "There is already a node/station at that location!"
      already name: "There is already a station with the same name!"
      no such station: "There is no such station!"
      cannot remove node: "You cannot remove node that is a station, use removestation command!"
      no such node: "There is no such node!"
      to itself: "You cannot link a node to itself!"
      one line: "Linked nodes must lay on one line!"
      empty: "empty"
      nodes: "Nodes:"
      stations: "Stations:"
      list: "List"
      invalid name: "Station name is invalid! Requirements: length: < 16, characters: letters, numbers, _."
config:
   prohibited stations:
      - "cancel"
      - "current"
      - "closest"
      - "info"
      - "list"
backup:
   ticks between backups: 36000
      