lang:
  cyrillic decoding: true
  commands:
    no access: "У вас нет доступа к этой команде!"
    usage: "Использование: "
    fatal error: "Произошла ошибка при исполнение команды!"
    no station: "Такой станции/команды нет."
    sit: "Садитесь в вагонетку и начинайте движение."
    canceled: "Путь сброшен!"
    destination: "Текущее направление: "
    place block: "Сначала поставьте контрольный блок и рельсы!"
    place station: "Сначала поставьте блок станции и рельсы!"
    adding node: "Добавление нового контрольного блока..."
    adding station: "Добавление новой станции..."
    fail reason: "Неудача! Причина: "
    adding success: "Успешно добавлено!"
    removing: "Удаление..."
    removing success: "Успешно удалено!"
    stand over: "Вы должны стоять над контрольным блоком!"
    no such node: "Узел не найден"
    linking: "Связывание..."
    linking success: "Успешно связано!"
    or: "или"
    and: "и"
    enter add node: "Введите команду для регистрации контрольного блока: "
    enter add station: "Введите команду для регистрации станции блока: "
    cannot break: "Вы не можете сломать зарегистрированный контрольный блок!"
    searching path: "Поиск пути..."
    path not found: "Пути в место назначения не существует, или вы уже находитесь на месте!"
    path found: "Путь найден. Начинаем движение..."
    no destination: "Направление не задано!"
    station: "Станция"
    node: "Узел"
    id: Id
    location: "Местоположение:"
    x: X
    y: Y
    z: Z
    connection: "Связь:"
    north: "Север"
    east: "Восток"
    south: "Юг"
    west: "Запад"
    name: "Название"
    no such command: "Нет такой подкоманды для: "
    name reserved: "Вы не можете использовать это название!"
    arrived: "Вы прибыли!"
    already location: "Тут уже есть контрольный блок!"
    already name: "Станция с таким название уже существует!"
    no such station: "Станция не найдена!"
    cannot remove node: "Вы не можете удалить узел, который является станцией, используйте removestation!"
    to itself: "Вы не можете связать узел с самим собой!"
    one line: "Связываемые узлы должны находиться на одной линии!"
    empty: "пусто"
    nodes: "Узлы:"
    stations: "Станции:"
    list: "Список"
    invalid name: "Названии станции может содержать лишь буквы, цифры, подчеркивание и иметь длину не более 16 символов!"
    repath: "Упс! Вы пропустили поворот? Позвольте нам всё исправить..."
    cannot touch: "Новый контрольный блок не может прикасаться к уже существующему!"
    invalid direction: "Доступные направления: north, east, south, west!"
    no link: "Этот узел ни с чем не связан в указанном направлении!"
    unlink success: "Связь удалена!"
config:
  prohibited stations:
  - cancel
  - current
  - closest
  - info
  - list
backup:
  ticks between backups: 36000
