main: com.radiantai.gox.GoX
version: 0.2
name: GoX_Plugin

commands:
   go:
      description: Basic /go command.
   gom:
      description: Command /gom for plugin admins.
      
permissions:
   GoX.Go:
      description: Gives access to basic commands performed with /go
      default: op
   GoX.GoM:
      description: Gives access to admin commands performed with /gom
      default: op