main: com.radiantai.gox.GoX
version: 1.3.3_beta
name: GoX

commands:
   go:
      description: Command for plugin users.
   gom:
      description: Command for plugin moderators.
      
permissions:
   GoX.Go:
      description: Gives access to basic commands performed with /go
      default: op
   GoX.GoM:
      description: Gives access to moderator commands performed with /gom
      default: op