main: com.radiantai.gox.GoX
version: 1.1.0
name: GoX_Plugin

commands:
   go:
      description: Basic /go command.
   gom:
      description: Command /gom for plugin moderators.
      
permissions:
   GoX.Go:
      description: Gives access to basic commands performed with /go
      default: op
   GoX.GoM:
      description: Gives access to moderator commands performed with /gom
      default: op